# Generated by Django 5.2.5 on 2025-10-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('overlapping_emotions', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True)),
                ('pitch_tempo', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('music_link', models.URLField(blank=True)),
                ('tags', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('instrument_type', models.CharField(max_length=100)),
                ('popularity_trend_score', models.FloatField()),
                ('metric_source', models.CharField(max_length=100)),
                ('license_typ', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
